version: '3.8'

services:
  mysql:
    image: mysql:8.0 # MySQL 8.0 이미지를 사용
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: spring # Spring 설정에서 사용된 데이터베이스 이름
      MYSQL_ROOT_PASSWORD: root # root 사용자 비밀번호 (Spring 설정과 일치)
    ports:
      - "3306:3306" # 로컬의 3306 포트를 컨테이너의 3306 포트에 매핑

volumes:
  mysql-data:
